### PR TITLE
[WEB-1127] style: create and delete modals' consistency

### PR DESCRIPTION
**Pull request by aaryan610**
#### Improvements:

1. Made all the delete modals consistent by creating a global delete modal file which provides the layout and UI, all the functionality is handled using props.
2. Made the following changes on all the create modals-
    - Updated the modal titles.
    - Fixed the casing, placeholders, button texts.
    - Added a separator between the footer and body of the modals.
    - Made the spacing between the input fields and sections consistent.

#### Media:

1. Delete modal

| Before | After |
|--------|--------|
| image | image | 

#### Affected modals:

1. API token create and delete.
2. Cycle create, edit and delete.
3. Estimate create, edit and delete.
4. Inbox issue create, accept, decline and delete.
5. Issue create, edit and delete.,
6. Issue attachment delete.
7. Label delete.
8. Module create, edit and delete.
9. Page create and delete.
10. State delete.
11. Project View create, edit and delete.
12. Webhook create, edit and delete.
13. Workspace View create, edit and delete.

#### Plane issue: [WEB-1127](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/06c5c4c1-204c-44f9-9087-44e6102fb52e)

### CODE REVIEW

**Review by SatishGandham — CHANGES_REQUESTED** [review]
Hi @aaryan610 , thanks for taking up this refactor.
To keep the modal behavior consistent, we can go one step further.
Lets have a core modal component, that takes position as a parameter and make the delete modal extend it.

This way we will have consistent behavior in-terms of how the modal opens.

In this change, ensure that we don't change the behaviour in vertical position of these two modals in smaller devices.

Delete modal moves from center to bottom on small devices, and create modal doesn't on mobiles.

**Comment by SatishGandham** [comment]
At certain widths, the modal is sticking to the edges. If it's a small change, see if you can handle this in this PR.
Screenshot 2024-05-06 at 12 30 38 PM

**Comment by aaryan610** [comment]
> At certain widths, the modal is sticking to the edges. If it's a small change, see if you can handle this in this PR. Screenshot 2024-05-06 at 12 30 38 PM

Took care of this with the lates commit.

**Review by SatishGandham — APPROVED** [review]
Looks good.

**Pull request merged**
