### PR TITLE
Add support for Claude-2, Cohere Llama2, CodeLlama, Azure OpenAI, Replicate LLMs (100+LLMs)

### PR DESCRIPTION
**Pull request by ishaan-jaff**
This PR adds support for the above mentioned LLMs using LiteLLM https://github.com/BerriAI/litellm/ 
LiteLLM is a lightweight package to simplify LLM API calls - use any llm as a drop in replacement for gpt-3.5-turbo. 

Example
```python
from litellm import completion

## set ENV variables
os.environ["OPENAI_API_KEY"] = "openai key"
os.environ["COHERE_API_KEY"] = "cohere key"

messages = [{ "content": "Hello, how are you?","role": "user"}]

# openai call
response = completion(model="gpt-3.5-turbo", messages=messages)

# cohere call
response = completion(model="command-nightly", messages)

# anthropic call
response = completion(model="claude-instant-1", messages=messages)
```

### CODE REVIEW

**Comment by ishaan-jaff** [comment]
@pablohashescobar @vihar can i get a review on this PR ? 

happy to add docs/tests if this initial commit looks good

**Comment by krrishdholakia** [comment]
bump on this? @Palanikannan1437 @aaryan610 @pablohashescobar

**Comment by sriramveeraghanta** [comment]
Dear @ishaan-jaff and @krrishdholakia,

We are developing a novel approach to enhance our platform by integrating additional AI engines. This improves the overall integration process and provides a more seamless experience.

**Comment by pablohashescobar** [comment]
@ishaan-jaff, thank you for contributing to Plane.

**Pull request merged**
