### PR TITLE
Added the quick-setup powershell file

### PR DESCRIPTION
**Pull request by Pdzly**
Its an experimental setup but it works correctly. ( The [2] Download and install Plane from source code" is instable because the windows compiling is broken right now see on discords support forum. ) But the rest functions well. ( I am a powershell beginner so please dont expect perfect or even good code! )

With it windows users only need to culthis file ( with for curl and curl.exe --output setup.ps1 --url https://raw.githubusercontent.com/Pdzly/plane/feature/quick-start-windows/plane_setup.ps1 ) and yes curl.exe is newly added to windows :) and then they just execute this file and it asks them the required parameters. ( URL for now ).

It requires only 1 thing:

Git installed 
Have windows updated.

### CODE REVIEW

**Comment by NarayanBavisetti** [comment]
Hi @Pdzly ,
Thank you for your contribution to Plane. While running the script, we encountered some errors related to file paths and command execution.
In addition, could you please take a look at the attached screenshot? It provides further details about the errors we encountered. Any insights or suggestions you may have would be greatly appreciated. 

o

**Comment by Pdzly** [comment]
> Hi @Pdzly , Thank you for your contribution to Plane. While running the script, we encountered some errors related to file paths and command execution. In addition, could you please take a look at the attached screenshot? It provides further details about the errors we encountered. Any insights or suggestions you may have would be greatly appreciated.
> 
> o

Yeah this happens when the user didnt installed git for every user ( aka C:\Program Files\Git ) 

But i swapped it out with the windows native bash ( on more updated windows machines ).

**Comment by Pdzly** [comment]
Thanks!

**Comment by NarayanBavisetti** [comment]
Hi @Pdzly, there was an error while I was running the scripts, looks like the .env was not created. I have attached the screenshot of it. Please take a look on it.
l (1)

**Comment by NarayanBavisetti** [comment]
Hi @Pdzly, just to update you, we have made some changes to the process. As a result, we are now mounting the environment variables.  Thank you for your valuable input and contribution.

**Pull request closed without merging**
