### PR TITLE
Clean up docker compose file for selfhosting

### PR DESCRIPTION
**Pull request by Robin-Sch**
### Removed nginx container (might want to put it back?)
I think the majority of people who will selfhost plane are selfhosting more than just plane, and this way the nginx container doesn't conflict with their current setup (port 80 is most likely already in use).
Maybe show/guide on how to setup a simple nginx server (in case they haven't done so)?

### Changed the order, first the important stuff (plane) and later the database/redis
For example, to upgrade to a different version or change port(s) you don't have to scroll all the way down anymore
Also I don't think anyone will ever change something with the redis/postgres instance?

### All containers are in the same format
First container_name, then image, then restart etc..
Just standardization, and looks better

### Removed links
Links are deprecated since compose version 2, all containers are in one docker network

### Removed build from plane-api
Now you don't have to download the whole repo anymore, just for the api image

### Removed ports from redis and postgresql
They can communicate freely with each other without exposing the port, increases the security since the postgres and redis instances aren't accessible from the outside

### Removed PGDATA environment variable
It's the default one and by removing it's less clutter in the file

### Renamed redis and db to plane-redis and plane-db
This way you know the redis and postgres containers belong to plane and aren't just named "redis" and "db"

### Could still be improved
The environment variables could be included in the `.env` file to remove them from the compose file and making the compose file more readable and smaller [see this](https://docs.docker.com/compose/environment-variables/set-environment-variables/#use-the-env_file-attribute)
This way you can change all environment variables from the `.env` file and they aren't spread across two files.

https://github.com/makeplane/plane/issues/1019

### CODE REVIEW

**Comment by Igorgro** [comment]
> Changed spacing to tabs for better readability

Use tabs instead of spaces is a bad idea for YAML files

**Comment by vihar** [comment]
Thank you, folks, for your contributions. We are still testing different options, and this temporary unstable fix is just one of them. Our team is actively working on finding a permanent solution. We appreciate your contribution and will review it and merge it soon.

**Comment by Web-eWorks** [comment]
> Removed ports from redis and postgresql
> They can communicate freely with each other without exposing the port, increases the security since the postgres and redis instances aren't accessible from the outside

I'd like to second this change - because the nginx instance and all of Plane's services are on the same Docker network, binding host ports is not required for communication between services. Exposing these services via bound host ports represents a security issue in single-server production environments; only the nginx proxy port needs to be accessible outside of the docker network for upstream traffic.

**Comment by Robin-Sch** [comment]
> Use tabs instead of spaces is a bad idea for YAML files

My bad, I changed it to 4 spaces after I noticed tabs not working (that's why the multiple fix spacing commits)

> I'd like to second this change - because the nginx instance and all of Plane's services are on the same Docker network, binding host ports is not required for communication between services. Exposing these services via bound host ports represents a security issue in single-server production environments; only the nginx proxy port needs to be accessible outside of the docker network for upstream traffic.

Port 3000 (frontend) and 8000 (backend) are required if you want to run plane without the nginx container (or use your own reverse proxy).

**Review by pablohashescobar — APPROVED** [review]

**Comment by pablohashescobar** [comment]
Merging this off, thank you for you contribution @Robin-Sch. Will update the documentation for users with and without nginx.

**Comment by Robin-Sch** [comment]
https://github.com/makeplane/plane/issues/1019#issuecomment-1568079328

See @require-dev's suggestion too

**Pull request merged**
