### PR TITLE
feat: add GitLab OAuth client

### LINKED ISSUE #4630: [bug]: docker-entrypoint-migrator.sh & docker-entrypoint-beat.sh loss execute privilege in linux
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I do docker compose in linux，I got such error:
[+] Running 13/15
 ✔ Network plane-master_dev_env          Created                                                    0.1s 
 ✔ Volume "plane-master_redisdata"       Created                                                    0.0s 
 ✔ Volume "plane-master_pgdata"          Created                                                    0.0s 
 ✔ Volume "plane-master_uploads"         Created                                                    0.0s 
 ✔ Container plane-master-plane-minio-1  Started                                                   23.8s 
 ✔ Container plane-master-plane-db-1     Started                                                   23.8s 
 ✔ Container plane-master-plane-redis-1  Started                                                   23.8s 
 ⠏ Container plane-master-migrator-1     Starting                                                  24.6s 
 ✔ Container plane-master-api-1          Started                                                   24.1s 
 ✔ Container plane-master-worker-1       Started                                                   24.5s 
 ⠦ Container plane-master-beat-worker-1  Starting                                                  24.6s 
 ✔ Container plane-master-web-1          Created                                                   11.3s 
 ✔ Container plane-master-space-1        Created                                                   12.1s 
 ✔ Container plane-master-admin-1        Created                                                   12.1s 
 ✔ Container plane-master-proxy-1        Created                                                    0.0s 
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "./bin/docker-entrypoint-migrator.sh": permission denied: unknown

I find that /apiserver/bin/docker-entrypoint-migrator.sh & /apiserver/bin/docker-entrypoint-beat.sh don't have execute privilege

### Steps to reproduce

1. ./setup.sh
2. docker compose -f docker-compose-local.yml up -d

### Environment

Production

### Browser

Google Chrome

### Variant

Local

### Version

master

### PR DESCRIPTION
**Pull request by almereyda**
This adds a GitLab OAuth client, based on the Google and GitHub examples.

To raise exceptions when OAuth is malconfigured, it also adds an additional `OAUTH_NOT_CONFIGURED` error.

There is a bit of code duplication between admin, web and spaces, but that may be a design choice.

This has been tested successfully against a custom GitLab instance and should work similarly against the default instance.

addresses #408
addresses #413

### CODE REVIEW

**Comment by almereyda** [comment]
As it turns out, I didn't find a place to document the added environment variables.

Should this PR here be accompanied by a parallel one in [makeplane/docs](https://github.com/makeplane/docs)?

**Comment by almereyda** [comment]
Rebased to accommodate 36b82a777682868274c3c8b1577f79e88097c79f

**Review by pablohashescobar — APPROVED** [review]

**Comment by sriramveeraghanta** [comment]
@almereyda 

Thank you for your contribution. We have merged your pull request into an internal branch for validation and testing. We will soon merge these changes into the `master` branch along with the updates for our next release.

**Comment by almereyda** [comment]
Thanks! I'm very excited.

Please test things out. The last rebase unfortunately removed the three commit version and put everything into a single commit again. I'm worried I've rebased the wrong branch, but hope I've catched the correct state of the implementation.

Please let me know if you run into any issues.

**Comment by almereyda** [comment]
My intuitin was correct. In trying to react quick with a rebase, I didn't pull my force-pushed working branch before attempting it, which resulted in me pushing an outdated state of the PR.

Thank you for being so diligent in checking this out into an internal feature branch.

Please reset it hard by `HEAD~1` and replace it with what is presented in:

- #4828

🙈

**Comment by sriramveeraghanta** [comment]
Our team will take over from here. We will test it to ensure everything is working and address any issues that arise during the testing process.

**Comment by almereyda** [comment]
Thanks for the notice. Feel free to reuse, recommit or remix the content of the PRs in any way.

Also feel free to close #4828, if suitable.

**Pull request merged**
