### PR TITLE
remove noHeader prop & show navigation as burger menu on [workspaceSlug] page, mobile screens

### PR DESCRIPTION
**Pull request by kblueberry**
This is a fix to bug #1332 [bug]: Unable to navigate via mobile on [workspaceSlug] page

### CODE REVIEW

**Comment by redzumi** [comment]
@aaryan610 hi! Pls, check this PR
PWA mode also broken, cuz I can'n navigate anywhere (in browser I can manualy change url to '/projects' and navigate to projects page where navigation drawer works fine)

**Comment by aaryan610** [comment]
Hi @kblueberry, thanks for your contribution to this bug. But, the approach used by you won't be feasible, as it will add an unnecessary topbar on the workspace dashboard.

Thanks for bringing this bug to our attention. It will be fixed once PR #1389 is merged.

**Comment by redzumi** [comment]
@aaryan610 thank you!
By the way, does the plane have design guidelines? Possibly, @kblueberry or me could fix things like this by myself in future

**Comment by aaryan610** [comment]
@redzumi we are actively working on creating a well structured documentation for our contributors and we plan to release it soon.

**Comment by redzumi** [comment]
@aaryan610 thanks for the help and replies!

**Pull request closed without merging**
