### PR TITLE
Add execute permissions to docker-entrypoint-beat.sh and docker-entrypoint-migrator.sh

### LINKED ISSUE #4630: [bug]: docker-entrypoint-migrator.sh & docker-entrypoint-beat.sh loss execute privilege in linux
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I do docker compose in linux，I got such error:
[+] Running 13/15
 ✔ Network plane-master_dev_env          Created                                                    0.1s 
 ✔ Volume "plane-master_redisdata"       Created                                                    0.0s 
 ✔ Volume "plane-master_pgdata"          Created                                                    0.0s 
 ✔ Volume "plane-master_uploads"         Created                                                    0.0s 
 ✔ Container plane-master-plane-minio-1  Started                                                   23.8s 
 ✔ Container plane-master-plane-db-1     Started                                                   23.8s 
 ✔ Container plane-master-plane-redis-1  Started                                                   23.8s 
 ⠏ Container plane-master-migrator-1     Starting                                                  24.6s 
 ✔ Container plane-master-api-1          Started                                                   24.1s 
 ✔ Container plane-master-worker-1       Started                                                   24.5s 
 ⠦ Container plane-master-beat-worker-1  Starting                                                  24.6s 
 ✔ Container plane-master-web-1          Created                                                   11.3s 
 ✔ Container plane-master-space-1        Created                                                   12.1s 
 ✔ Container plane-master-admin-1        Created                                                   12.1s 
 ✔ Container plane-master-proxy-1        Created                                                    0.0s 
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "./bin/docker-entrypoint-migrator.sh": permission denied: unknown

I find that /apiserver/bin/docker-entrypoint-migrator.sh & /apiserver/bin/docker-entrypoint-beat.sh don't have execute privilege

### Steps to reproduce

1. ./setup.sh
2. docker compose -f docker-compose-local.yml up -d

### Environment

Production

### Browser

Google Chrome

### Variant

Local

### Version

master

### PR DESCRIPTION
**Pull request by mrigankpawagi**
Very small fix. Resolved #4630. The issue occurs in the development system also.

### CODE REVIEW

**Comment by almereyda** [comment]
Instead of changing the commands, it's also possible to fix this more permanently right inside the git repository. I ran

```sh
chmod u+x apiserver/bin/docker-entrypoint-beat.sh
chmod u+x apiserver/bin/docker-entrypoint-migrator.sh
```

Git then offered me the files to be added to the staging area:

```sh
git add apiserver/bin/docker-entrypoint-beat.sh
git add apiserver/bin/docker-entrypoint-migrator.sh
```

This also fixes the development environment and appears to produce a smaller change set.

**Comment by mrigankpawagi** [comment]
Thanks for your response, @almereyda. Are you able to run the development system though?

**Comment by almereyda** [comment]
Yes, I have been developing #4692 based on the fix directly in the repository.

**Comment by mrigankpawagi** [comment]
I see... I am unable to run the development environment properly because the `plane-beat-worker` and `plane-migrator` containers keep shutting down.

**Comment by almereyda** [comment]
Maybe this is another issue to be investigated independently?

If you liked you could try it with cherry picking the patch from the other repository.

Allow me to exemplify this idea with a fresh clone:

```sh
git clone https://github.com/makeplane/plane.git
cd plane
git remote add allmende https://github.com/allmende/plane.git
git fetch allmende
git cherry-pick 49fefd1ced23211ab9c0dc9d28d641908c0d0a88
./setup.sh
docker compose -f docker-compose-local.yml config | yq '.services | keys' | cut -d" " -f2 | xargs -L1 docker compose -f docker-compose-local.yml build
docker compose -f docker-compose-local.yml up -d plane-db plane-minio plane-redis
docker compose -f docker-compose-local.yml up migrator
docker compose -f docker-compose-local.yml up -d
```

This is a series of steps that helps me achieve a long-running plane instance accessible at http://localhost.

```sh
$ docker compose -f docker-compose-local.yml ps -a
NAME                   IMAGE                  COMMAND                  SERVICE       CREATED              STATUS                          PORTS
plane-admin-1         plane-admin           "docker-entrypoint.s…"   admin         2 minutes ago        Up About a minute               3000/tcp
plane-api-1           plane-api             "./bin/docker-entryp…"   api           2 minutes ago        Up About a minute               8000/tcp
plane-beat-worker-1   plane-beat-worker     "./bin/docker-entryp…"   beat-worker   2 minutes ago        Up About a minute               8000/tcp
plane-migrator-1      plane-migrator        "./bin/docker-entryp…"   migrator      6 minutes ago        Exited (0) About a minute ago   
plane-plane-db-1      postgres:15.2-alpine   "docker-entrypoint.s…"   plane-db      7 minutes ago        Up 7 minutes                    5432/tcp
plane-plane-minio-1   minio/minio            "/usr/bin/docker-ent…"   plane-minio   7 minutes ago        Up 7 minutes                    9000/tcp
plane-plane-redis-1   redis:7.2.4-alpine     "docker-entrypoint.s…"   plane-redis   7 minutes ago        Up 7 minutes                    6379/tcp
plane-proxy-1         plane-proxy           "/docker-entrypoint.…"   proxy         About a minute ago   Up About a minute               0.0.0.0:80->80/tcp, :::80->80/tcp
plane-space-1         plane-space           "docker-entrypoint.s…"   space         2 minutes ago        Up About a minute               4000/tcp
plane-web-1           plane-web             "docker-entrypoint.s…"   web           2 minutes ago        Up About a minute               3000/tcp
plane-worker-1        plane-worker          "./bin/docker-entryp…"   worker        2 minutes ago        Up About a minute               8000/tcp
```

**Comment by mrigankpawagi** [comment]
I see, thanks a lot for sharing this. Let me see if I can make it work with your steps.

**Comment by sriramveeraghanta** [comment]
As noted by @almereyda, the resolution of this issue will be addressed by GitLab OAuth pull request #4692. Therefore, we will be closing this pull request.

**Pull request closed without merging**
