### PR TITLE
feat: add helm chart

### PR DESCRIPTION
**Pull request by jordibeen**
This PR contains a Helm Chart which enables a quick and painless deployment of Plane's `v0.12.2-dev` on Kubernetes.

People would like to self-host plane on Kubernetes, but because there's no Helm Chart for Plane yet, it's currently mandatory to create custom K8s configuration files for this. After building a custom helm chart for self-hosting Plane, I spent a few hours to be able to give it back to the community. It's loosely based on [Superset's Helm chart](https://github.com/apache/superset/tree/master/helm/superset), and contains an extensive [README.md](https://github.com/jordibeen/plane/tree/helm-chart/helm-chart), as well as a prepackaged redis as postgresql.

## Installation
Configure a [values file](https://helm.sh/docs/chart_template_guide/values_files/) containing overwrites of the environment variables such as credentials and secret keys, and then run:
`helm install plane plane/helm-chart -f [overwrites.yaml]`

## Missing Ingress
Because we use [traefik](https://traefik.io/) for our production cluster, I've added [traefik IngressRoutes](https://doc.traefik.io/traefik/routing/providers/kubernetes-crd/#kind-ingressroute) for routing `plane.example.com` and `plane-api.example.com` to their respective services. Using these requires Traefik to be installed. It'd be nicer if the chart would use the default [Kubernetes Ingress](https://kubernetes.io/docs/concepts/services-networking/ingress/) CRD's instead. Contributions for this are highly appreciated.

Alternatively, you can verify the installation by port forwarding both the frontend as well as the API.
- `kubectl port-forward svc/plane-web 3000:3000`
- `kubectl port-forward svc/plane-api 8000:8000`

After this, Plane will now be running at http://localhost:3000/ 🎉 

## Missing Minio
I'm using AWS S3 storage. I have decided not to include minio for now.

---
This PR also fixes https://github.com/makeplane/plane/issues/723 and  https://github.com/makeplane/plane/issues/1455.

### CODE REVIEW

**Comment by jordibeen** [comment]
Note that I'm currently unable to update the helm-chart to support the latest `v0.13.2-dev` because of [this issue](https://github.com/makeplane/plane/issues/2434). Will update the chart to support the latest version when this issue is fixed.

**Comment by Kelsinga** [comment]
@jordibeen 
in the ingressroutes web.yaml and api.yaml you refer to 
.Values.web.ingressRoute.host and .Values.web.ingressRoute.tls.secretName
.Values.api.ingressRoute.host and .Values.api.ingressRoute.tls.secretName

But I think you meant to reference planeFrontend and planeApi

**Comment by manishg3** [comment]
We have published the helm charts and are available at [Artifact Hub](https://artifacthub.io/packages/helm/makeplane/plane-ce)

**Comment by rouja** [comment]
Hello,

@mguptahub where is the source  code of the helm chart that you published ? Is-it possible to contrib  to it ?

**Pull request closed without merging**
